### PR TITLE
- added support for delete All, update Attributes, Non numeric ID attribute of node and match all that supports IN type query

### PR DESCRIPTION
**Pull request by denisbetsi**
The existing code was attempting to treat all IDs as integers, in case of any string like GUID, it'd simply not work. So this version has support non numeric IDs

Match All, had a function passing filter data as parameter, so when sending a list of IDs in an array to search, it'd attempt to search inq:[array] which would produce no results. So had to re-write the search query for IN to function. 

Updating attributes wasn't fully implemented and same for deleteAll which gets called occasionally even if you aren't deleting multiple items. This version includes support for those 2.

### CODE REVIEW

**Comment by haio** [comment]
Hi, @denisbetsi [this](https://github.com/IndustrialCloudSolutions/loopback-connector-neo4j/pull/2/files#diff-a1e15c50174d2ba3a7e568c7721c41a1R135) will simply replace the node with given attributes, it seems not what `updateAttributes` should do. The cypher support update node by 
`start n=node(id) set n += {data} return n`

**Comment by denisbetsi** [comment]
It's much quicker to replace all values instead of doing comparison of what has changed and then updating Changed only attributes. It can be modified to issue a query to return existing values and then do quick comparison and do an update of changed only attributes, however that will create additional overhead. 

Currently it's doing the set n+={data} which in fact replaces entire content of the node vs updating individual attributes. 

I do see an issue with this in multi user environment where one person updates let's say Name attribute and another one is issuing a later update on City, would cause name update to be overridden during the physical update.

**Comment by haio** [comment]
I dont think `n += {data}` is `doing comparison of what has changed and then updating Changed only attributes`, it add new attribute if not exists, otherwise override it. And the current code is `n = {data}` which will replaces entire node. For example:
{ name: 'name' }  += { age: 0 } will be { name: 'name', age: 0 }
{ name: 'name' }  = { age: 0 } will be { age: 0 }
The first case is what updateAttributes should be.

**Comment by denisbetsi** [comment]
Modified updateAttributes now to support update on changed attributes only

https://github.com/IndustrialCloudSolutions/loopback-connector-neo4j/pull/3

**Pull request merged**
